max-quantity: 640

gui:
  max-quantity: 640
  category-selection-gui:
    title: "カテゴリー選択"
    item-format:
      display-name: "&6%display-name% &8| &6%category-name%"
      lore:
       - "%category-description%"
  category-gui-title: "%category-name%"
  transaction-item-format:
    display-name: "&6%item-name% &8| &6%category-name%" # display-nameが指定されていない場合は無視されてデフォルトの名前が表示される。
    lore:
      - ""
      - "&7* 左クリックで &b%quantity% &7個預け入れ *"
      - "&7* 右クリックで &b%quantity% &7個取り出し *"
      - ""
      - "&7在庫: &b%stock% 個"
  buy-and-sell-item-format:
    display-name: "&6%item-name% &8| &6%category-name%"
    lore:
      - ""
      - "&7* 左クリックで &b%quantity% &7個購入 *"
      - "&7* 右クリックで &b%quantity% &7個売却 *"
      - ""
      - "&7所持金: &b%balance% 円"
      - "&7買価: &b%buy-price% 円"
      - "&7売価: &b%sell-price% 円"
      - "&7在庫: &b%stock% 個"
  craft-item-format:
    display-name: "&6%item-name% &8| &6%category-name%"
    lore:
      - ""
      - "&7* 左クリックで &b%quantity% &7回分(&b%amount%&7個)作成 *"
      - ""
      - "&7在庫: &b%stock% 個"
      - "&7素材:"
      - "%materials%" # このプレースホルダーは複数行を挿入します。プレースホルダー以外の文字は無視されます。
    materials-placeholder-format: "&7  %material%: %material-stock% / %amount%"
  page-function-items:
    previous-page:
      display-name: "&6前のページ &8| &6Previous Page"
      lore: []
    decrease:
      display-name: "&c減らす"
      lore: []
    change-unit:
      display-name: "&7増減単位を変更 (右クリックで1/2倍、クリックで2倍)"
      lore:
        - ""
        - "&7* 右クリックで1/2倍、クリックで2倍 *"
        - ""
    increase:
      display-name: "&b増やす"
      lore: []
    back-menu:
      display-name: "&6戻る &8| &6Return"
      lore: []
    transaction:
      display-name: "&f引き出し・預け入れ"
      lore:
        - ""
        - "&7* クリックで引き出し・預け入れモードにする *"
        - "&7* Shift + 右クリックで手持ちの全てのアイテムを預ける *"
        - ""
    buy-and-sell:
      display-name: "&f売り買い"
      lore:
        - ""
        - "&7* クリックで売買モードにする *"
        - "&c* Shift + 右クリックで手持ちの全てのアイテムを売却する *"
        - ""
    craft:
      display-name: "&fクラフト"
      lore:
        - ""
        - "&7* クリックでクラフトモードにする *"
        - ""
    next-page:
      display-name: "&6次のページ &8| &6Next Page"
      lore: []

sound-settings: # 効果音設定 固定ピッチの音はminとmaxの平均となる。ランダムピッチの場合はminとmaxの間をとった後、それが2以上の場合は2に切り詰められる。
  open: # メニューを開く, カテゴリークリック時
    sound: BLOCK_CHEST_OPEN
    pitch: [1.0, 1.0] # [min, max]
    volume: [1.0, 1.0] # [min, max]
  deposit: # 拾う and 預ける
    sound: ENTITY_ITEM_PICKUP
    pitch: [1.5, 3.0] #2の確率を上げる。
    volume: [1.5, 3.0]
  withdraw: # 取り出す
    sound: BLOCK_STONE_BUTTON_CLICK_ON
    pitch: [1.0, 1.0]
    volume: [1.0, 1.0]
  buy: # 買う
    sound: ENTITY_ITEM_PICKUP
    pitch: [1.0, 1.0]
    volume: [1.0, 1.0]
  sell: # 売る
    sound: BLOCK_STONE_BUTTON_CLICK_ON
    pitch: [1.0, 1.0]
    volume: [1.0, 1.0]
  craft: # 作成する
    sound: BLOCK_ANVIL_PLACE
    pitch: [0.8, 0.8]
    volume: [0.1, 0.1]
  not-enough: # 不足
    sound: ENTITY_ENDERMAN_TELEPORT
    pitch: [1.0, 1.0]
    volume: [1.0, 1.0]
  decrease-unit: # 単位を減らす
    sound: BLOCK_TRIPWIRE_CLICK_OFF
    pitch: [1.0, 1.0]
    volume: [1.0, 1.0]
  increase-unit: # 単位を増やす
    sound: BLOCK_TRIPWIRE_CLICK_ON
    pitch: [1.0, 1.0]
    volume: [1.0, 1.0]
  back: # 前のメニューに戻る
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    pitch: [1.0, 1.0]
    volume: [1.0, 1.0]
  change-page: # 同じメニュー内でページを変更する
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    pitch: [1.0, 1.0]
    volume: [1.0, 1.0]
auto-store: # 自動格納
  enabled: true # 自動格納を鯖設定として有効化するか
  default: false # プレイヤーの初期設定
disabled-worlds: # 使えなくするワールド
  - Playground
  - Jail

# TODO: 別PLで実装
auto-replant-worlds: # Boxの在庫から自動植え直しを行うワールド
  - public_facility

box-stick: # 左手に持つとアイテムをデータベースから使うための棒。DisplayNameやLoreなどを変えても昔の棒は機能する。
  display-name: "&9Box Stick"
  lore:
    - "§r"
    - "§7利き手じゃない手にこれを持つと、利き手の"
    - "§7アイテムを使った時にBoxから消費します。"