General: # PL設定
  SoundSetting: # 効果音設定
    Pitch: 1.0
    Volume: 1.0
    Sounds:
      Open: BLOCK_CHEST_OPEN # メニューを開く, カテゴリークリック時
      TakeIn: ENTITY_ITEM_PICKUP # 拾う and 預ける
      TakeOut: BLOCK_STONE_BUTTON_CLICK_ON # 取り出す
      NotEnough: ENTITY_ENDERMAN_TELEPORT # 不足
      Decrease: BLOCK_TRIPWIRE_CLICK_OFF # 単位を減らす
      Increase: BLOCK_TRIPWIRE_CLICK_ON # 単位を増やす
      ReturnToSelectionGui: ENTITY_EXPERIENCE_ORB_PICKUP # カテゴリ選択GUIに戻る
      ChangePage: ENTITY_EXPERIENCE_ORB_PICKUP # ページ変更
  AutoStore: # 自動格納
    Enabled: true # 自動格納を鯖設定として有効化するか
    PlayerDefault: false # プレイヤーの初期設定
  DisableWorld: # 使えなくするワールド
    - Playground
    - lobby_5
    - Jail
