General: # PL設定
  SoundSetting: # 効果音設定
    Pitch: 1.0
    Volume: 1.0
    Sounds:
      Open: BLOCK_CHEST_OPEN # メニューを開く, カテゴリークリック時
      TakeIn: ENTITY_ITEM_PICKUP # 拾う and 預ける
      TakeOut: BLOCK_STONE_BUTTON_CLICK_ON # 取り出す
      NotEnough: ENTITY_ENDERMAN_TELEPORT # 不足
      Decrease: BLOCK_TRIPWIRE_CLICK_OFF # 単位を減らす
      Increase: BLOCK_TRIPWIRE_CLICK_ON # 単位を増やす
      ReturnToSelectionGui: ENTITY_EXPERIENCE_ORB_PICKUP # カテゴリ選択GUIに戻る
      ChangePage: ENTITY_EXPERIENCE_ORB_PICKUP # ページ変更
  AutoStore: # 自動格納
    Enabled: true # 自動格納を鯖設定として有効化するか
    PlayerDefault: false # プレイヤーの初期設定
  DisabledWorld: # 使えなくするワールド
    - Playground
    - lobby_5
    - Jail
  ReplantWorld:
    - pf
  BoxStick: # 左手に持つとアイテムをデータベースから使うための棒。DisplayNameやLoreなどを変えても昔の棒は機能する。
    Enabled:
      BlockPlace: true # ブロック設置時に自動補充
      Food: true # 食べたときに自動補充
      Potion: true # ポーション投げ放題
      Tool: true # エンチャントや名前付けや説明文などのアイテムメタがない、耐久力を持つアイテムを自動補充。
    DisplayName: "&9Box Stick"
    Lore:
      - "&r"
      - "§7利き手じゃない手にこれを持つと、利き手の"
      - "§7アイテムを使った時にBoxから消費します。"
