name: ${project.artifactId}
version: ${project.version}
api-version: "1.14"
main: ${project.groupId}.${project.artifactId}
author: LazyGon
softdepend: ["Vault"]
commands:
  box:
    description: Base Command of Box plugin.
    aliases: [box, okobox, b]
  boxadmin:
    description: Admin Command of Box plugin.
    aliases: [boxadmin]
    permission: boxadmin

permissions:
# command permissions
  boxadmin.*:
    description: Includes all admin command permissions.
    default: op
    children:
      boxadmin.addcategory: true
      boxadmin.autostore: true
      boxadmin.autostorelist: true
      boxadmin.give: true
      boxadmin.help: true
      boxadmin.reload: true
      boxadmin.set: true
      boxadmin.take: true
      boxadmin: true
  boxadmin:
    default: op
  boxadmin.addcategory:
    default: op
  boxadmin.autostore:
    default: op
  boxadmin.autostorelist:
    default: op
  boxadmin.give:
    default: op
  boxadmin.help:
    default: op
  boxadmin.reload:
    default: op
  boxadmin.set:
    default: op
  boxadmin.take:
    default: op
  boxadmin.creative:
    default: false
  box.*:
    description: Includes all normal command permissions.
    default: op
    children:
      box.autostore: true
      box.autostorelist: true
      box.withdraw: true
      box.deposit: true
      box.give: true
      box.help: true
      box.version: true
      box.stick.*: true
  box.autostore:
    default: true
  box.autostorelist:
    default: true
  box.withdraw:
    default: true
  box.deposit:
    default: true
  box.give:
    default: true
  box.help:
    default: true
  box.version:
    default: true
  box.stick.*:
    default: true
    children:
      box.stick: true
      box.stick.block: true
      box.stick.food: true
      box.stick.potion: true
      box.stick.tool: true
  box.stick:
    default: true
  box.stick.block:
    default: true
  box.stick.food:
    default: true
  box.stick.potion:
    default: true
  box.stick.tool:
    default: true