General: # PL設定
  SoundSetting: # 効果音設定
    Pitch: 1.0
    Volume: 1.0
    Sounds:
      Open: BLOCK_CHEST_OPEN # メニューを開く, カテゴリークリック時
      TakeIn: ENTITY_ITEM_PICKUP # 拾う and 預ける
      TakeOut: BLOCK_STONE_BUTTON_CLICK_ON # 取り出す
      NotEnough: ENTITY_ENDERMAN_TELEPORT # 不足
      Decrease: BLOCK_TRIPWIRE_CLICK_OFF # 単位を減らす
      Increase: BLOCK_TRIPWIRE_CLICK_ON # 単位を増やす
      ReturnToSelectionGui: ENTITY_EXPERIENCE_ORB_PICKUP # カテゴリ選択GUIに戻る
      ChangePage: ENTITY_EXPERIENCE_ORB_PICKUP # ページ変更
  AutoStore: # 自動格納
    Enabled: true # 自動格納を鯖設定として有効化するか
    PlayerDefault: false # プレイヤーの初期設定
  DisableWorld: # 使えなくするワールド
    - Playground
    - lobby_5
    - Jail

Migration: # 移行設定 (スコアボードとItemIDの組み合わせ)
  Combination: # itemID: scoreboard
    DIRT: boxDirt
    GRASS_BLOCK: boxGrass
    COARSE_DIRT: boxCoarsedirt
    PODZOL: boxPodzol
    MYCELIUM: boxMycelium
    GRAVEL: boxGravel
    Clay: boxClay
    SAND: boxSand
    SANDSTONE: boxSandstone
    CHISELED_SANDSTONE: boxChiseledSand
    CUT_SANDSTONE: boxCutsandstone
    SANDSTONE_SLAB: boxSandstoneSlab
    SANDSTONE_STAIRS: boxSandStairs
    SMOOTH_SANDSTONE: boxSmoothSand
    RED_SAND: boxRedSand
    RED_SANDSTONE: boxRedsandstone
    CHISELED_RED_SANDSTONE: boxChiseledRSand
    CUT_RED_SANDSTONE: boxCutRsandstone
    RED_SANDSTONE_SLAB: boxRSandstoneSl
    RED_SANDSTONE_STAIRS: boxRSandStairs
    SMOOTH_RED_SANDSTONE: boxSmoothRSand
    COBBLESTONE: boxCobblestone
    MOSSY_COBBLESTONE: boxMCobblestone
    COBBLESTONE_SLAB: boxCobblestoneSl
    COBBLESTONE_STAIRS: boxCobblestoneSt
    GRANITE: boxGranite
    DIORITE: boxDiorite
    ANDESITE: boxAndesite
    COBBLESTONE_WALL: boxCstoneWall
    MOSSY_COBBLESTONE_WALL: boxMCstoneWall
    STONE_SLAB: boxStoneSlab
    SMOOTH_STONE: boxSmoothStone
    POLISHED_GRANITE: boxPGranite
    POLISHED_DIORITE: boxPDiorite
    POLISHED_ANDESITE: boxPAndesite
    STONE: boxStone
    STONE_BRICKS: boxStoneBricks
    CHISELED_STONE_BRICKS: boxChiseledstone
    STONE_BRICK_SLAB: boxStoneBrickSl
    STONE_BRICK_STAIRS: boxStoneBrickSt
    COAL_ORE: boxCoalore
    IRON_ORE: boxIronore
    GOLD_ORE: boxGoldore
    REDSTONE_ORE: boxRedstoneore
    LAPIS_ORE: boxLapisore
    DIAMOND_ORE: boxDiamondore
    EMERALD_ORE: boxEmeraldore
    COAL: boxCoal
    IRON_INGOT: boxIroningot
    GOLD_INGOT: boxGoldingot
    REDSTONE: boxRedstone
    LAPIS_LAZULI: boxLapislazuli
    DIAMOND: boxDiamond
    EMERALD: boxEmerald
    ICE: boxIce
    PACKED_ICE: boxPackedIce
    BLUE_ICE: boxBlueIce